// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn_R_ulrOEGvyEk3JDAyddyi8w348p0D4',
    appId: '1:747127064515:web:428bb7c716df9704191f76',
    messagingSenderId: '747127064515',
    projectId: 'agroscan-firebase',
    authDomain: 'agroscan-firebase.firebaseapp.com',
    storageBucket: 'agroscan-firebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVeYGlmAGCADOSR7jrB9BogbnpF5SP_r0',
    appId: '1:747127064515:android:2877aa423651e042191f76',
    messagingSenderId: '747127064515',
    projectId: 'agroscan-firebase',
    storageBucket: 'agroscan-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNxZGZ9zUFmJKEYFb5iQ0lBcGZQBLB84k',
    appId: '1:747127064515:ios:39e92fb2cf07acdc191f76',
    messagingSenderId: '747127064515',
    projectId: 'agroscan-firebase',
    storageBucket: 'agroscan-firebase.firebasestorage.app',
    iosBundleId: 'com.example.agriscan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNxZGZ9zUFmJKEYFb5iQ0lBcGZQBLB84k',
    appId: '1:747127064515:ios:39e92fb2cf07acdc191f76',
    messagingSenderId: '747127064515',
    projectId: 'agroscan-firebase',
    storageBucket: 'agroscan-firebase.firebasestorage.app',
    iosBundleId: 'com.example.agriscan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn_R_ulrOEGvyEk3JDAyddyi8w348p0D4',
    appId: '1:747127064515:web:30eaf5769e7911df191f76',
    messagingSenderId: '747127064515',
    projectId: 'agroscan-firebase',
    authDomain: 'agroscan-firebase.firebaseapp.com',
    storageBucket: 'agroscan-firebase.firebasestorage.app',
  );
}
